### PR TITLE
Add Declarations pattern

### PR DESCRIPTION
**Pull request by Rhodine-orleans-lindsay**
Added pattern for declarations

Addresses: https://github.com/UKHomeOffice/design-system/issues/390

### CODE REVIEW

**Comment by daniel-ac-martin** [comment]
Looks good from a technical point of view.

@DeborahStevenson: What do you think? Is this good for a first pass?

**Comment by DeborahStevenson** [comment]
@daniel-ac-martin looks good to me.

Under 'Research' it says to 'get in touch'.  Can we change this please to say:

More research is needed. If your service uses this pattern, email design@digital.homeoffice.gov.uk to share your user research findings.


Can we make the email a link please?  Thanks

**Comment by Rhodine-orleans-lindsay** [comment]
@daniel-ac-martin Sure no problem, I can do that. @DeborahStevenson - several of the other patterns are similarly worded in the 'Research' section as 'get in touch' (I think because the email is in the 'Get in Touch' section'). Do we want to change the wording in the Research section for those patterns too?

**Comment by DeborahStevenson** [comment]
In that case, I think leave the wording as 'get in touch' and ignore my changes for now.  I'll take a proper look at it and get it signed off with others before changing it   across all patterns.

However, I think the 'get in touch' text should be a link to the email address across all of the patterns.  Are you able to just add the link please?

Thanks

Debbie


Deborah Stevenson
Senior Content Designer
Migration and Borders Technology Portfolio (MBTP)
Digital, Data and Technology (DDaT), Corporate Enablers

Home Office

________________________________

**Comment by daniel-ac-martin** [comment]
@DeborahStevenson: I wonder if we should link to a page instead. Perhaps?: https://design.homeoffice.gov.uk/contribute/discuss-on-github

**Review by daniel-ac-martin — CHANGES_REQUESTED** [review]
@Rhodine-orleans-lindsay: Could you link 'get in touch' to the GitHub discussion for the pattern?: https://github.com/UKHomeOffice/design-system/discussions/378

Looks good otherwise. :-)

**Comment by DeborahStevenson** [comment]
I think it depends how we want people to contact us?

For now, I think I'd add the email link but open to discussing.



Deborah Stevenson
Senior Content Designer
Migration and Borders Technology Portfolio (MBTP)
Digital, Data and Technology (DDaT), Corporate Enablers

Home Office

________________________________

**Pull request merged**
