### PR TITLE
Add letter pattern

### PR DESCRIPTION
**Pull request by tomyems**
Following discussion https://github.com/UKHomeOffice/design-system/discussions/377, and resolves issue https://github.com/UKHomeOffice/design-system/issues/458.

Contribute to the discussion for design feedback, and the issue or pull request for development feedback or iterations.

### CODE REVIEW

**Comment by tomyems** [comment]
https://633aabbca7b24e4143196396--hods.netlify.app/patterns/send-a-letter

**Comment by Sarah-Lombardi** [comment]
Looking at it, some shading on the blocks may help differentiate them. Also can we make the address line its own element?

**Comment by Sarah-Lombardi** [comment]
And the sentence starting 'this guidance sets out...' is probably not useful. I'd say cut it.

**Comment by Sarah-Lombardi** [comment]
I'd also go for 'main letter content' and 'additional letter content' as titles for the different models. I wanted to specify that the standard paragraphs go after the main letter so they don't distract, so it would be the last page. But it might make people think that they have to keep their main body strictly to one page.

**Comment by Sarah-Lombardi** [comment]
- In research section, 'infred' should be 'informed'
- In the block for 'standard content' there should be a comma before 'if applicable', then a list lead in like 'such as:'
- In 'What to include in a letter', 'official log' should be 'official logo' and 'thesignature' needs a space

**Comment by tomyems** [comment]
https://63402bb447e213111ee70022--hods.netlify.app/patterns/send-a-letter

**Comment by tomyems** [comment]
https://63402f5df8e580141894c955--hods.netlify.app/patterns/send-a-letter

**Comment by tomyems** [comment]
https://63510d6e8cddf900b234eb51--hods.netlify.app/patterns/send-a-letter

**Comment by tomyems** [comment]
https://63513998886e1c1f978d1836--hods.netlify.app/patterns/send-a-letter

**Review by daniel-ac-martin — APPROVED** [review]
SCSS code could go in another place.
But it's not a big deal.
LGTM otherwise.

**Comment by tomyems** [comment]
@daniel-ac-martin The accessibility team have raised a possible improvement. The structure of the page which is shown visually, we don't think is available to a user using a screen reader. Is there something we could do to make this available to them, to make the structure semantic as well as visual?

**Comment by daniel-ac-martin** [comment]
@tomyems: I think I'd have to defer to the accessibility team on that one!
i.e. Are they able to recommend anything?

**Comment by tomyems** [comment]
The best suggestion was some aria. If nothing springs to mind, I'd be inclined to continue, and list this as a potential improvement. There's two broad points, one is the left/right split, which we could resolve by calling them the 'left block' and 'right block', and the other is which elements are inside which blocks (which is at the moment only visually apparent)

**Comment by tomyems** [comment]
https://637cb6ba731dbc03e943fb37--hods.netlify.app/patterns/send-a-letter

**Comment by tomyems** [comment]
https://637d0469f3661000608af927--hods.netlify.app/patterns/send-a-letter

**Comment by tomyems** [comment]
Clarified that it's only for posted letters: https://638090c15737096c0e176c29--hods.netlify.app/patterns/send-a-letter

**Comment by tomyems** [comment]
Fixed content: https://638092e327e28361a9f48c53--hods.netlify.app/patterns/send-a-letter

**Review by daniel-ac-martin — APPROVED** [review]
LGTM.

(I can move the SCSS code later.)

**Pull request merged**
