### PR TITLE
Voice and tone: Link directly to discussion

### PR DESCRIPTION
**Pull request by daniel-ac-martin**
Updates the GitHub discussion link to go directly to the relevant discussion.

### CODE REVIEW

**Comment by daniel-ac-martin** [comment]
@Sarah-Lombardi: Do we want this? Or is it better to just link to the main discussions page?

**Comment by Sarah-Lombardi** [comment]
> @Sarah-Lombardi: Do we want this? Or is it better to just link to the main discussions page?

You’re right. It should link to the discussion itself. Good spot.

**Comment by daniel-ac-martin** [comment]
> > @Sarah-Lombardi: Do we want this? Or is it better to just link to the main discussions page?
> 
> You’re right. It should link to the discussion itself. Good spot.

Okay. Do you want to approve this change then? Thinks to think about:
- Have I linked to the right discussion?
- Have you taken a look at the preview? (Click 'view deployment' of the 'Details' link next to 'Netlify' in the list of checks at the bottom.)

It's best practice for someone else to review these. ;-)

**Comment by daniel-ac-martin** [comment]
@MylesMudaHO: Bit of a silly one (as it's so small), but do you want to review this from a technical perspective?

**Review by MylesMudaHO — APPROVED** [review]
As it's a simple link change and it correctly redirects to the discussion page in the current deployment, it looks good to me!

**Pull request merged**
