### PR TITLE
Sex gender pattern

### PR DESCRIPTION
**Pull request by Sallytolson**

### CODE REVIEW

**Review by daniel-ac-martin — APPROVED** [review]
This seems fine from a technical perspective.

I wonder if it's helpful to be explicit about when 'other' is a valid option or not. (Perhaps with a second example.) The text covers this though.

I also wonder if it's worth pointing out that due to _low cardinality_, it's often not very helpful to ask for sex as it doesn't narrow down a set of search results as much as other information would, for example.

**Comment by daniel-ac-martin** [comment]
Oh just noticed...

Are we linking to the correct GitHub discussion at the bottom of the page?

**Review by tomyems — CHANGES_REQUESTED** [review]
I wonder if we should include a 'Writing for this pattern' section for this page, to perhaps help designers:
* understand the purpose behind the 'why we ask this question' text, and so help them write it
* ask this question when the type of travel document is known, such as it has to be a passport

We should link back to the sex and gender discussion (https://github.com/UKHomeOffice/design-system/discussions/347) in the 'help us improve this pattern'.

The content and pattern looks good. Couple of quick questions, how important is 'their' in the title, does it work without it? In the headings I wondered what you thought about 'ask' rather than 'asking'?

I've got a few suggestions for improving the menu on the left-hand side too, which we can try at the same time. :)

**Comment by tomyems** [comment]
Link to test version: https://64b163bce12a1529c427d37c--hods.netlify.app/patterns/ask-sex-or-gender

**Review by tomyems — APPROVED** [review]

**Comment by tomyems** [comment]
With services described rather than named: https://64b94899fbb1810f7256c143--hods.netlify.app/patterns/ask-sex-or-gender

**Comment by daniel-ac-martin** [comment]
*Note:* Please squash these commits.

**Review by daniel-ac-martin — APPROVED** [review]

**Pull request merged**
