### PR TITLE
Added Layout & Typography guidance plus updated sidebar nav for all a…

### PR DESCRIPTION
**Pull request by ildrinn**
…ccessibility pages

### CODE REVIEW

**Review by daniel-ac-martin — CHANGES_REQUESTED** [review]
The https://61b0c6391f63032daf99180b--hods.netlify.app/accessibility page itself needs to have the link added.

Looks fine to me otherwise.

@MarionDownie: Do you want to check the content?

**Comment by MarionDownie** [comment]
Hi Susi, have some comments on the layout page itself:

1. Use single quotation marks throughout, eg around ‘em’

2. (em) is also like this later on - be consistent 

3. Some rogue letters at start of sentences - in table:
SMay use strong magnification and only see a small part of the page

Under the Fonts heading:
AThe Home Office

4. First line of the table - space missing:

Use clear and readable fonts Don’t use italics or ALL CAPS

5. Break these up into sentences/paras, as they're a bit long:

Make sure your design is flexible enough to still work with larger text - inside buttons or table cells, for example. Users should be able to zoom up to 300% without losing page function. 

Your service must work in both landscape (horizontal) and portrait (vertical) orientations, for users who may not have a choice in which orientation they use, For example, a paraplegic user with a device attached to their wheelchair in a fixed orientation.

**Comment by guermanc** [comment]
Changes were made by @ildrinn and are in https://github.com/UKHomeOffice/design-system/pull/319

**Comment by guermanc** [comment]
Amendments incorporated into #319 and merged.

**Pull request closed without merging**
