### PR TITLE
Add writing for status messages

### PR DESCRIPTION
**Pull request by tomyems**
Fixes https://github.com/UKHomeOffice/design-system/issues/462

See discussion: https://github.com/UKHomeOffice/design-system/discussions/419

Following the standard page template: https://github.com/UKHomeOffice/design-system/discussions/430

### CODE REVIEW

**Comment by tomyems** [comment]
https://63524eaf8f87b55bd6bc4f67--hods.netlify.app/components?name=Status%20message

**Review by daniel-ac-martin — APPROVED** [review]
LGTM.

Do we need a second content person to look at this?

**Comment by tomyems** [comment]
Presented at design system working group. One comment to follow up on. To present between meetings or at the next meeting for approval.

**Comment by tomyems** [comment]
Updated and content reviewed.

**Pull request merged**
