### PR TITLE
Timeouts guidance page

### PR DESCRIPTION
**Pull request by guermanc**

### CODE REVIEW

**Review by MarionDownie — COMMENTED** [review]
This looks fine, but won't merge yet as there's more content to be added.

**Review by MarionDownie — COMMENTED** [review]
Ignore this

**Review by daniel-ac-martin — APPROVED** [review]

**Comment by daniel-ac-martin** [comment]
Nice work @guermanc. :-)

**Comment by MarionDownie** [comment]
Ah, we didn't want to merge this one yet, as there's more content to be added. @guermanc, have you finished working on the rest of this content yet? If so I can take a look at editing this one as a priority.

**Comment by guermanc** [comment]
Just running the rest of the content through some QA and will send it over as soon as that's complete!

**Pull request merged**
