### PR TITLE
GOV.UK Design System in Figma

### PR DESCRIPTION
**Pull request by joeedhorton**
Hi, 

I've added:

- GOV.UK Design System in Figma (link added to resources page)
- Update of new file added (link added in updates section on index.html)

It could be in the future: we split the prototyping page into sub categories of tools as the list is getting quite long and having the tools in brackets is easily missed. 

Let me know what you think. 

Joe

### CODE REVIEW

**Comment by karypun** [comment]
@MarionDownie : Hi Joe, I'm a bit confused as to exactly what this is for. Is it just a template file so people can use components of the GOV.UK design system for prototyping in Figma? If so, I think the title page is a bit confusing - it looks like a template for submitting something to the design system... Perhaps removing the blue header would help? The Home Office equivalent file is much more plain. Apologies if I'm completely misunderstanding this..

**Comment by karypun** [comment]
I don't think you can share the Transport font as it's proprietary. Can you remove? It's not shared on the GOV.UK design system. https://design-system.service.gov.uk/styles/typography/

**Comment by joeedhorton** [comment]
Hey @karypun and @MarionDownie,

- Are you referring to the thumbnail cover that is blue or the getting started page?
- Just waiting to hear back from GDS as they are reviewing the file – hoping to get a confirmation from them around linking the typeface 👍 

Joe

**Comment by karypun** [comment]
This is now on the GOV.UK design system and in our Get started section

**Pull request closed without merging**
